apiVersion: v1
kind: PersistentVolume
metadata:
  name: slaves-postgresql-databases
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: "jenkins-postgresql-data"
    fsType: "ext4"