apiVersion: v1
kind: ReplicationController
metadata: 
  name: jenkins
  labels: 
    name: jenkins
spec: 
  replicas: 1
  template: 
    metadata: 
      name: jenkins
      labels: 
        name: jenkins
    spec: 
      containers: 
        - name: jenkins
          image: sysbind/jenkins-master:2.41
          imagePullPolicy: Always         
          ports: 
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts: 
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes: 
        - name: jenkins-data
          gcePersistentDisk:
            pdName: jenkins-data-disk
            fsType: ext4