apiVersion: v1
kind: Service
metadata:
    name: jenkins-slave
spec:
    type: NodePort
    selector: 
        name: jenkins
    ports:
      - name: http
        port: 50000
        nodePort: 32050
        protocol: TCP
